name = "backend"
compatibility_date = "2023-12-01"

[[r2_buckets]]
binding = 'R2_UPLOAD'
bucket_name = 'blog-app-bucket'

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzI0ODUzOTMtMmI1OC00NWI1LWE4OWUtMThmZDhhM2UzMzI4IiwidGVuYW50X2lkIjoiYWMxN2M2YzgzN2NkMjM1N2JjNGEwMjE3YTQ1NWQxYWI1NWIyNDIxZGE4MzUzNjc4OGRlOGMwZGFkNzM2NGEwMiIsImludGVybmFsX3NlY3JldCI6Ijk3YjY0N2VhLTAwZjktNDI3ZS05NThjLTVjOGU3OWJhNWZkNSJ9.ctSoxVfzDIG57NcVO3oEO4QO38DsPlEqpLZn0CDRHP8"

JWT_SECRET="secret"
OPENAI_API_KEY="sk-proj-GB2qgnaakoAcTgWEaBxbT3BlbkFJ2VQXXN9u3DKY05Zylsz0"
R2_SUBDOMAIN_URL="https://pub-f4df79dafd534d86873fafaeb876140b.r2.dev"